CREATE TABLE IF NOT EXISTS users
(
    id         UUID PRIMARY KEY,
    name       CHARACTER VARYING NOT NULL,
    email      CHARACTER VARYING NOT NULL,
    password   CHARACTER VARYING NOT NULL,
    created_at TIMESTAMP         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP         NOT NULL DEFAULT CURRENT_TIMESTAMP
);