with-expecter: True
dir: "./mocks/{{.PackageName}}"
filename: "mock_{{.InterfaceName | snakecase}}.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mock{{.PackageName}}"
all: True
packages:
  github.com/pauloRohling/txplorer/internal/domain/repository:
    config:
      all: True
  github.com/pauloRohling/txplorer/pkg/transaction:
    config:
      all: True