// Code generated by mockery v2.50.0. DO NOT EDIT.

package mockaccount

import (
	context "context"

	account "github.com/pauloRohling/txplorer/internal/domain/account"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddBalanceById provides a mock function with given fields: ctx, id, balance
func (_m *MockRepository) AddBalanceById(ctx context.Context, id uuid.UUID, balance int64) (*account.Account, error) {
	ret := _m.Called(ctx, id, balance)

	if len(ret) == 0 {
		panic("no return value specified for AddBalanceById")
	}

	var r0 *account.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) (*account.Account, error)); ok {
		return rf(ctx, id, balance)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) *account.Account); ok {
		r0 = rf(ctx, id, balance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64) error); ok {
		r1 = rf(ctx, id, balance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_AddBalanceById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBalanceById'
type MockRepository_AddBalanceById_Call struct {
	*mock.Call
}

// AddBalanceById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - balance int64
func (_e *MockRepository_Expecter) AddBalanceById(ctx interface{}, id interface{}, balance interface{}) *MockRepository_AddBalanceById_Call {
	return &MockRepository_AddBalanceById_Call{Call: _e.mock.On("AddBalanceById", ctx, id, balance)}
}

func (_c *MockRepository_AddBalanceById_Call) Run(run func(ctx context.Context, id uuid.UUID, balance int64)) *MockRepository_AddBalanceById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int64))
	})
	return _c
}

func (_c *MockRepository_AddBalanceById_Call) Return(_a0 *account.Account, _a1 error) *MockRepository_AddBalanceById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_AddBalanceById_Call) RunAndReturn(run func(context.Context, uuid.UUID, int64) (*account.Account, error)) *MockRepository_AddBalanceById_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, userId
func (_m *MockRepository) Create(ctx context.Context, userId uuid.UUID) (*account.Account, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *account.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*account.Account, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *account.Account); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uuid.UUID
func (_e *MockRepository_Expecter) Create(ctx interface{}, userId interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, userId)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, userId uuid.UUID)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 *account.Account, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*account.Account, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetById(ctx context.Context, id uuid.UUID) (*account.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *account.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*account.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *account.Account); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockRepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetById(ctx interface{}, id interface{}) *MockRepository_GetById_Call {
	return &MockRepository_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockRepository_GetById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetById_Call) Return(_a0 *account.Account, _a1 error) *MockRepository_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetById_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*account.Account, error)) *MockRepository_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserId provides a mock function with given fields: ctx, userId
func (_m *MockRepository) GetByUserId(ctx context.Context, userId uuid.UUID) (*account.Account, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserId")
	}

	var r0 *account.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*account.Account, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *account.Account); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserId'
type MockRepository_GetByUserId_Call struct {
	*mock.Call
}

// GetByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uuid.UUID
func (_e *MockRepository_Expecter) GetByUserId(ctx interface{}, userId interface{}) *MockRepository_GetByUserId_Call {
	return &MockRepository_GetByUserId_Call{Call: _e.mock.On("GetByUserId", ctx, userId)}
}

func (_c *MockRepository_GetByUserId_Call) Run(run func(ctx context.Context, userId uuid.UUID)) *MockRepository_GetByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetByUserId_Call) Return(_a0 *account.Account, _a1 error) *MockRepository_GetByUserId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByUserId_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*account.Account, error)) *MockRepository_GetByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
