CREATE TABLE IF NOT EXISTS users
(
    id         UUID PRIMARY KEY,
    name       CHARACTER VARYING        NOT NULL,
    email      CHARACTER VARYING UNIQUE NOT NULL,
    password   CHARACTER VARYING        NOT NULL,
    created_at TIMESTAMP                NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP                NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);